---
- hosts: k8s-cluster
  gather_facts: false
  vars:
    ansible_ssh_pipelining: false
  roles:
   - { role: bootstrap-os, tags: bootstrap-os}

- hosts: all
  gather_facts: true

- hosts: k8s-cluster
  vars:
    ansible_ssh_pipelining: true
  roles:
    - { role: glusterfs/server }


