---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Instal xfs package
- name: install xfs Debian
  apt: name=xfsprogs state=present
  when: ansible_os_family == "Debian"

- name: install xfs RedHat
  yum: name=xfsprogs state=present
  when: ansible_os_family == "RedHat"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

